<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find user using username and clear-text password
     *
     * @param string $username
     * @param string $password
     * @return null|User
     */
    public function getByUsernameAndPassword(string $username, string $password)
    {
        return $this->findOneBy(array(
            'email' => $username,
            'password_hash' => User::hashPassword($password)
        ));
    }
}
